base:
  project: Heart Disease Classification-project
  random_state: 42
  target_col: target

data_source:
  s3_source: heart.csv

load_data:
  raw_dataset_csv: inference_heart_disease.csv

split_data:
  train_path: data/processed/train_winequality.csv
  test_path: data/processed/test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      #alpha: 0.90
      #l1_ratio: 0.01
      alpha: 0.000001
      l1_ratio: 0.01
model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet wine regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://127.0.0.1:5000
