base:
  project: Heart Disease Classification-project
  random_state: 42
  target_col: target

data_source:
  s3_source: data_given/heart.csv

load_data:
  raw_dataset_csv: data/raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.2

estimators:
  Adaboost:
    params:
      n_estimators: [10, 20, 40, 50, 60, 70, 80, 90, 100]
      learning_rate: [0.05, 0.1, 0.5, 1.0]
      algorithm: ['SAMME', 'SAMME.R']
      #alpha: 0.90
      #l1_ratio: 0.01
      #alpha: 0.000001
      #l1_ratio: 0.01
model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

webapp_model_dir: prediction_service/models/model1_adaboost.joblib

scaler_dir: prediction_service/models/scaler.save 

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet wine regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://127.0.0.1:5000
